baseurl: ""
url: https://www.firstsource.io/
title: Quanto Informatique SARL
email: ashkan@binary.com
author: Ashkan
description: "Quanto Informatique SARL is the financial markets research and development centre of the Binary.com group of companies. Charged with developing the complex pricing technologies that underpin the Binary.com website, Quanto Informatique employs a team of dedicated Quantitative Analysts and market data research scientists from its base in Paris."
copyright:
credits:

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed
